pipelines:
  branches:
    develop:
      - step:
          name: Test App
          image: node:10.15.3
          caches:
            - node
          script:
            - rm -rf package-lock.json
            - rm -rf node_modules
            - npm install
            - npm run test


      - step:
          name: Create artifact
          image: node:10.15.3
          script:
            - git archive --format=tar.gz develop -o application.tar.gz
          artifacts:
            - application.tar.gz

      - step:
          name: Deploy to heroku
          image: node:10.15.3
          deployment: staging
          caches:
            - node
          script:
            - pipe: atlassian/heroku-deploy:1.1.4
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $HEROKU_STAGING #http://uberfortutor-react-staging.herokuapp.com/
                ZIP_FILE: "application.tar.gz"
                WAIT: "true"
      
      - step:
          name: Run test Katalon
          image: katalonstudio/katalon
          services:
            - docker
          script:
            # Run Test
            - cd Tests && katalonc.sh -statusDelay=30 -retry=0 -testSuitePath="Test Suites/TS_RegressionTest" -executionProfile="staging" -browserType="Chrome (headless)" -apiKey=80d69c36-4a5d-4fe9-8628-502a92cee8a8                                                                                                                                                                    
          artifacts: # defining the artifacts .
            - report/**
    master:
      - step:
          name: Deploy App
          image: node:10.15.3
          caches:
            - node
          script:
            - rm -rf package-lock.json
            - rm -rf node_modules
            - npm install
            - npm run test

      - step:
          name: Create artifact
          image: node:10.15.3
          script:
            - git archive --format=tar.gz master -o application.tar.gz
          artifacts:
            - application.tar.gz

      - step:
          name: Deploy to heroku
          image: node:10.15.3
          deployment: production
          caches:
            - node
          script:
            - pipe: atlassian/heroku-deploy:1.1.4
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $HEROKU_PROD #http://uberfortutor-react.herokuapp.com/
                ZIP_FILE: "application.tar.gz"
                WAIT: "true"
